name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - publish
jobs:
  get_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Clone private digital garden
        uses: actions/checkout@v3
        with:
          repository: "kucukkanat/digital-garden"
      - name: List them
        run: |
          ls -l
    

