name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - publish
jobs:
  get_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repo
        working-directory: "./repos"
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Clone private digital garden
        working-directory: "./repos"
        uses: actions/checkout@v3
        with:
          repository: "kucukkanat/digital-garden"
          ref: "main"
          token: ${{ secrets.REPO_CLONE_TOKEN }}
      - name: List them
        working-directory: "./repos"
        run: |
          ls -l
          tree
          echo "FINISHED"
    

